"""del table admin

Revision ID: 042534f14074
Revises: b9971ea3355f
Create Date: 2023-09-10 01:52:33.925850

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '042534f14074'
down_revision = 'b9971ea3355f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.drop_index('ix_admin_email')
        batch_op.drop_index('ix_admin_username')

    op.drop_table('admin')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_admin')

    op.create_table('admin',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=64), nullable=True),
    sa.Column('email', sa.VARCHAR(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.create_index('ix_admin_username', ['username'], unique=False)
        batch_op.create_index('ix_admin_email', ['email'], unique=False)

    # ### end Alembic commands ###
